
flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 1f9c923a4d55ea700aa98a83d99836a3c419385b
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: 5ebefbadeefa99e35e97d558f93f2597c0c85b09
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 9d0a9d1afda4724bb167bf3ddc82b91d27ddfe7b
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: 27a23e33d00552821141cf2a46654df7ec4559b5

- location:
    git: git@github.com:ComputationWithBoundedResources/tct-trs
    commit: c3f6c31270b91a110d0948670d3c147a4b984893
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-its
    commit: e3590f53172ac328e5d8f2fc0a5eb8f88fbfa38e

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
- graphviz-2999.18.0.1
resolver: lts-3.4
