
flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 54beea4baf8f2ad1f02d86b4319512b6e70ab4a2
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: d535bce1db3ea4c76df3aa202bcac441365ece2b
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 6749fdef9fa092fe04d5e801977f663c656b4f65
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: b88ce5394cb9a7dde6d3a08a0a15391991e36ed5

- location:
    git: git@github.com:ComputationWithBoundedResources/tct-trs
    commit: a888652e9e3a12b595c29e6f0a5ddbbd25c1abfe
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-its
    commit: 9e72017a69382c76c7ccadc31214fed3488d767f

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
- graphviz-2999.18.0.1
resolver: lts-3.4
